### PR TITLE
It only works if you keep the naming convention

### PR DESCRIPTION
**Pull request by Gustorn**

### CODE REVIEW

**Comment by leios** [comment]
Wait, why? I was running it just fine on my machine. I just updated the makefile to use caps FDTD and it worked fine.

**Comment by Gustorn** [comment]
The Makefile relies on all of the following having the same name (case-sensitive):

1. binary name
2. .dat name
3. source file name
4. plot file name

You can change all 4 if you want, but it's easy to miss some.

**Comment by Gustorn** [comment]
I can change it so it adheres to some other pattern, but there must be a pattern, for exampel the following would still work:

1. binary: bin_<name>
2. dat: <name>.dat
3. source: <name>.cpp
4. plot_<name>.gp

I don't know if you can do case-insensitive stuff in Makefiles, but I'd rather not bother with it.

**Comment by leios** [comment]
I'll look into it, don't worry about it! Thanks again for all the help! =)

**Comment by leios** [comment]
Thanks again! =)

**Pull request merged**
